import { Customer, CustomerProfile, Conversation } from "@/types";

export const mockCustomers: Customer[] = [
  {
    id: "c1",
    user_id: "mock-user",
    name: "陳小姐",
    nickname: "陳小姐",
    gender: "女",
    birth_year: 1975,
    age: 51,
    occupation: "錶店店長",
    company: "個人商號",
    industry: "零售",
    phone: "0912-345-678",
    contact_info: "LINE：chen_watch",
    relationship_level: 3,
    notes: "",
    created_at: "2026-07-01T09:00:00+08:00",
    updated_at: "2026-09-06T18:30:00+08:00",
    current_focus: ["退休", "女兒畢業", "現金流"],
    next_step: "了解退休後每月生活費",
    last_contact_at: "2026-09-06",
  },
  {
    id: "c2",
    user_id: "mock-user",
    name: "王先生",
    nickname: "王先生",
    gender: "男",
    birth_year: 1971,
    age: 55,
    occupation: "公司負責人",
    company: "王氏五金",
    industry: "製造",
    phone: "0933-222-111",
    contact_info: "LINE：wang_ceo",
    relationship_level: 4,
    notes: "",
    created_at: "2026-05-10T09:00:00+08:00",
    updated_at: "2026-08-15T14:00:00+08:00",
    current_focus: ["傳承", "兩個孩子", "股票"],
    next_step: "了解他希望如何控制未來財產分配",
    last_contact_at: "2026-08-15",
  },
];

export const mockProfiles: Record<string, CustomerProfile> = {
  c1: {
    id: "p1",
    customer_id: "c1",
    family: ["女兒，大四", "單親扶養", "主要家庭責任：女兒"],
    work: ["錶店店長", "近期體力下降", "可能三年內考慮退休"],
    finance: {
      房屋: "已繳清",
      現金: "偏少",
      投資: "待了解",
      負債態度: "不喜歡負債",
    },
    property: {},
    life_goals: ["希望三年內降低工作量", "希望退休後不要依靠女兒"],
    concerns: ["安全感", "現金流", "不要增加子女負擔"],
    resistance: ["不喜歡借錢", "不喜歡一開始就談商品", "對長期綁約有疑慮"],
    decision_makers: ["本人"],
    competitors: [],
    preferences: {},
    updated_at: "2026-09-06T18:30:00+08:00",
  },
  c2: {
    id: "p2",
    customer_id: "c2",
    family: ["兩個孩子", "配偶協助管理公司"],
    work: ["公司負責人", "近期考慮交棒"],
    finance: { 股票: "為主要資產", 現金: "中" },
    property: { 廠房: "自有" },
    life_goals: ["希望公平安排兩個孩子的未來"],
    concerns: ["傳承", "股權分配"],
    resistance: ["對外人插手家族安排有戒心"],
    decision_makers: ["本人", "太太"],
    competitors: [
      { name: "李經理", company: "國泰保險", trust_level: "中" },
    ],
    preferences: {},
    updated_at: "2026-08-15T14:00:00+08:00",
  },
};

export const mockConversations: Record<string, Conversation[]> = {
  c1: [
    {
      id: "v1",
      customer_id: "c1",
      user_id: "mock-user",
      conversation_date: "2026-09-06T18:00:00+08:00",
      input_type: "voice",
      transcript:
        "今天跟陳小姐吃飯，她說女兒明年就大學畢業，最近自己工作也覺得很累，大概再三年就不想做了。但是她很排斥借錢，只要一聽到房貸就覺得壓力很大。目前她還沒有仔細算過退休之後需要多少生活費。",
      summary: "開始談到退休，女兒明年大學畢業，對房貸明顯抗拒",
      ai_analysis: null,
      created_at: "2026-09-06T18:30:00+08:00",
    },
    {
      id: "v0",
      customer_id: "c1",
      user_id: "mock-user",
      conversation_date: "2026-08-15T12:00:00+08:00",
      input_type: "text",
      transcript: "聊到工作，最近覺得體力開始下降。",
      summary: "聊到工作，最近覺得體力開始下降",
      ai_analysis: null,
      created_at: "2026-08-15T12:10:00+08:00",
    },
  ],
  c2: [],
};
